import os
Import('env')

#TODO: todo esto tomarlo del SConstruct
BOOST_ROOT_LIB = os.environ['BOOST_ROOT'] + '/stage/lib'
SRC_DIR = os.environ['DEV_CPP_HOME'] + '/schwimmer-hund/src/'
BIN_DIR = os.environ['DEV_CPP_HOME'] + '/schwimmer-hund/bin/'





#env.BuildDir( 'Z:/Development/CPP/schwimmer-hund/bin/', 'Z:/Development/CPP/schwimmer-hund/src/libs/os_services/test/' )
#env.BuildDir('build1/', 'src/')
#env.BuildDir('build2/', 'src/')


#env.Append( CPPPATH = [ os.environ['BOOST_ROOT'], 'Z:/Development/CPP/schwimmer-hund/src/' ] )
env.Append( CPPPATH = [ os.environ['BOOST_ROOT'], SRC_DIR ] )
env.Append( LIBPATH=[BOOST_ROOT_LIB] )

#env.Program('stress_test_creation_watcher', ['../../src/libs/os_services/test/stress_test_creation_watcher.cpp'])
#env.Program('stress_test_file_generator', ['../../src/libs/os_services/test/stress_test_file_generator.cpp'])
#env.Program('stress_test_file_generator_and_watcher', ['../../src/libs/os_services/test/stress_test_file_generator_and_watcher.cpp'])

#env.Program('test', ['../../src/libs/os_services/test/test.cpp'])
env.Program('test', ['Z:/Development/CPP/schwimmer-hund/src/libs/os_services/test/test.cpp'])
#env.Program('test', ['build/test.cpp'])






#print env.Dump()